// Generated by the UNAI Foundry -- observes real LLM provider calls this
// live app makes (via global fetch, used internally by most modern SDKs)
// and persists a running token total so "Run comparison live" can report a
// genuinely measured number instead of a modeled guess. Never invents
// traffic -- only counts what the app itself really sent while running.
import fs from "fs";
import path from "path";

// process.cwd() rather than a __dirname derived from import.meta.url: this
// file is imported as source in dev mode (tsx, real ESM) but esbuild bundles
// it INLINE into a single dist/server.cjs for the app's own "build" script --
// import.meta.url is empty in that CJS output, which crashed the whole
// server at startup (ERR_INVALID_ARG_TYPE) the first time this shipped.
// cwd is set by the launcher to the app's own root in both modes, so this
// works identically either way.
const HOSTS = /api\.openai\.com|api\.anthropic\.com|api\.mistral\.ai|generativelanguage\.googleapis\.com|api\.groq\.com|api\.together\.xyz|openrouter\.ai|localhost:11434|127\.0\.0\.1:11434/i;
const REPORT_PATH = path.join(process.cwd(), "unai_measure_report.json");
let tokensIn = 0, tokensOut = 0, calls = 0;

function flush() {
  try { fs.writeFileSync(REPORT_PATH, JSON.stringify({ tokensIn, tokensOut, calls })); } catch (_) {}
}
function extractUsage(json) {
  const usage = (json && (json.usage || json.usageMetadata)) || {};
  const inp = usage.input_tokens ?? usage.prompt_tokens ?? usage.promptTokenCount ?? 0;
  const outp = usage.output_tokens ?? usage.completion_tokens ?? usage.candidatesTokenCount ?? 0;
  return { inp: inp || 0, outp: outp || 0 };
}

const origFetch = globalThis.fetch;
if (origFetch) {
  globalThis.fetch = async function (url, opts) {
    const res = await origFetch(url, opts);
    const u = typeof url === "string" ? url : (url && url.url) || "";
    if (HOSTS.test(u)) {
      try {
        const json = await res.clone().json();
        const { inp, outp } = extractUsage(json);
        if (inp || outp) { tokensIn += inp; tokensOut += outp; calls++; flush(); }
      } catch (_) {}
    }
    return res;
  };
}
// Start every fresh live process from a clean, honest zero rather than a
// stale report left over from a previous run of this converted copy.
flush();
