# Generated by the UNAI Foundry -- observes real LLM provider calls this
# live app makes (via httpx, module-level or Client) and persists a running
# token total so "Run comparison live" can report a genuinely measured
# number instead of a modeled guess. Never invents traffic -- only counts
# what the app itself really sent while running.
import json, os, threading
import httpx

_LLM_HOSTS = ("api.groq.com", "api.openai.com", "generativelanguage.googleapis.com",
              "api.anthropic.com", "api.mistral.ai", "openrouter.ai")
_REPORT_PATH = os.path.join(os.path.dirname(os.path.abspath(__file__)), "unai_measure_report.json")
_lock = threading.Lock()
_tokens_in = 0
_tokens_out = 0
_calls = 0

def _is_llm_url(url):
    u = str(url)
    return any(h in u for h in _LLM_HOSTS)

def _extract_usage(resp):
    try:
        data = resp.json()
    except Exception:
        return 0, 0
    usage = data.get("usage") or data.get("usageMetadata") or {}
    inp = usage.get("prompt_tokens") or usage.get("input_tokens") or usage.get("promptTokenCount") or 0
    outp = usage.get("completion_tokens") or usage.get("output_tokens") or usage.get("candidatesTokenCount") or 0
    return inp or 0, outp or 0

def _flush():
    try:
        with open(_REPORT_PATH, "w") as f:
            json.dump({"tokensIn": _tokens_in, "tokensOut": _tokens_out, "calls": _calls}, f)
    except Exception:
        pass

def _record(inp, outp):
    global _tokens_in, _tokens_out, _calls
    with _lock:
        _tokens_in += inp or 0
        _tokens_out += outp or 0
        _calls += 1
        _flush()

def _maybe_record(url, resp):
    if _is_llm_url(url):
        inp, outp = _extract_usage(resp)
        if inp or outp:
            _record(inp, outp)

_orig_post = httpx.post
def _patched_post(url, *a, **kw):
    resp = _orig_post(url, *a, **kw)
    _maybe_record(url, resp)
    return resp
httpx.post = _patched_post

_orig_client_post = httpx.Client.post
def _patched_client_post(self, url, *a, **kw):
    resp = _orig_client_post(self, url, *a, **kw)
    _maybe_record(url, resp)
    return resp
httpx.Client.post = _patched_client_post

# Start every fresh live process from a clean, honest zero rather than a
# stale report left over from a previous run of this converted copy.
_flush()
