/* Generated by the UNAI Foundry convert-folder pipeline. Do not hand-edit --
 * re-running the conversion overwrites this file. */
const http = require("http");
const fs = require("fs");
const path = require("path");
const { spawn } = require("child_process");
const { UNAI } = require("./engine.cjs");
const { enrichEvidence } = require("./llm.cjs");

const MANIFEST = {
  "source": "build",
  "systems": [],
  "id": "AGT-PERSISTTEST",
  "createdAt": "2026-09-17T19:27:59.0511711+05:30",
  "description": "Verifies the auto-relaunch-on-restart fix.",
  "name": "Persistence Test Agent",
  "capabilities": [
    {
      "label": "Check Persistence",
      "systems": [],
      "id": "check_persistence"
    }
  ],
  "layers": 7,
  "governance": {
    "guardrails": [],
    "autonomyThresholdPct": 85,
    "valueLimitUsd": 50000
  }
};
const WORK_DIR = __dirname;
const STATIC_DIR_REL = null;
const MEASURE_SCRIPT = null;
const LIVE_INSTRUMENTED = false;
// Capability ids that actually cost real tokens in the SOURCE app (see
// convertFolder's realCostCapabilityIds) -- used to scope the UNAI side of
// "Run comparison live" down to an apples-to-apples subset instead of
// modeling cost for every detected capability, most of which the source app
// never spends a token on.
const REAL_COST_CAPABILITY_IDS = [];
const MIME = { ".html": "text/html", ".js": "application/javascript", ".css": "text/css", ".json": "application/json",
  ".svg": "image/svg+xml", ".png": "image/png", ".jpg": "image/jpeg", ".ico": "image/x-icon" };

function buildGoal() {
  return {
    name: MANIFEST.name, description: MANIFEST.description,
    gen1Agents: MANIFEST.capabilities.map(c => c.label),
    plan: MANIFEST.capabilities.map(c => ({ capability: "cv_" + c.id, agentEquiv: c.label, systems: (c.systems && c.systems.length) ? c.systems : ["ANALYTICS"] })),
  };
}
function runUnai() { return new UNAI({}).run(buildGoal()); }
// Same as runUnai() but scoped to just the given capability ids -- used by
// handleCompare() to match UNAI's side to the SAME narrow slice of work the
// source app actually pays real tokens for (see REAL_COST_CAPABILITY_IDS),
// instead of modeling cost for the whole manifest.
function runUnaiScoped(capabilityIds) {
  const subset = MANIFEST.capabilities.filter(c => capabilityIds.includes(c.id))
    .map(c => ({ capability: "cv_" + c.id, agentEquiv: c.label, systems: (c.systems && c.systems.length) ? c.systems : ["ANALYTICS"] }));
  if (!subset.length) return new UNAI({}).run(buildGoal());   // fall back to the whole plan if none matched
  const goal = { name: MANIFEST.name, description: MANIFEST.description, gen1Agents: subset.map(s => s.agentEquiv), plan: subset };
  return new UNAI({}).run(goal);
}

function runYourAppMeasured() {
  return new Promise(resolve => {
    // Live python-fullstack app: no harness to spawn -- httpx was patched
    // in-process (see unai_llm_capture.py) and writes its running total to
    // this same file on every real provider call the live app makes. Read
    // it directly; a real 0 (nothing captured yet) is reported honestly,
    // not disguised as a modeled fallback.
    if (LIVE_INSTRUMENTED) {
      try {
        const report = JSON.parse(fs.readFileSync(path.join(WORK_DIR, "unai_measure_report.json"), "utf8"));
        const tin = report.tokensIn || 0, tout = report.tokensOut || 0, calls = report.calls || 0;
        if (!calls) {
          return resolve({ measured: true, tokensIn: 0, tokensOut: 0, tokensTotal: 0, calls: 0,
            reason: "no real provider calls observed yet -- interact with the live app above (or hit its API), then run this comparison again" });
        }
        // Per-call AVERAGE, not the lifetime running total -- unai_measure_report.json
        // accumulates across every real call since this process started, but
        // UNAI's side (runUnaiScoped) models/measures a SINGLE pass. Comparing
        // a multi-call lifetime sum against a one-pass estimate would keep
        // drifting further apart the longer the live app runs, which isn't a
        // real efficiency signal -- just an artifact of when you happened to click.
        const avgIn = Math.round(tin / calls), avgOut = Math.round(tout / calls);
        return resolve({ measured: true, tokensIn: avgIn, tokensOut: avgOut, tokensTotal: avgIn + avgOut,
          calls, lifetimeTokensTotal: tin + tout, reason: null });
      } catch (e) {
        return resolve({ measured: false, tokensIn: 0, tokensOut: 0, tokensTotal: 0, reason: "could not read the live capture report: " + e.message });
      }
    }
    if (!MEASURE_SCRIPT) return resolve({ measured: false, tokensIn: 0, tokensOut: 0, tokensTotal: 0, reason: "no measurement harness available for this app" });
    const isPy = MEASURE_SCRIPT.endsWith(".py");
    const cmd = isPy ? (process.platform === "win32" ? "python" : "python3") : process.execPath;
    // Generous timeout: a multi-script/multi-agent app can make many sequential
    // real LLM calls (the GDC 4-agent app alone takes ~60-90s) — same reasoning
    // as the main server.js's own long-running-route timeouts.
    let child; try { child = spawn(cmd, [MEASURE_SCRIPT], { cwd: WORK_DIR, timeout: 240000 }); }
    catch (e) { return resolve({ measured: false, tokensIn: 0, tokensOut: 0, tokensTotal: 0, reason: e.message }); }
    let err = ""; child.stderr.on("data", b => err += b);
    const finish = () => {
      try {
        const report = JSON.parse(fs.readFileSync(path.join(WORK_DIR, "unai_measure_report.json"), "utf8"));
        const tin = report.tokensIn || 0, tout = report.tokensOut || 0;
        resolve({ measured: (tin + tout) > 0, tokensIn: tin, tokensOut: tout, tokensTotal: tin + tout,
          reason: (tin + tout) > 0 ? null : "harness ran but captured no real provider usage" });
      } catch (e) { resolve({ measured: false, tokensIn: 0, tokensOut: 0, tokensTotal: 0, reason: "measurement harness failed: " + (err.slice(0, 200) || e.message) }); }
    };
    child.on("close", finish); child.on("error", finish);
  });
}
function modeledYourApp(out) {
  const b = out.observability && out.observability.benchmark && out.observability.benchmark.baseline;
  return b ? { measured: false, tokensIn: b.tokensIn, tokensOut: b.tokensOut, tokensTotal: b.tokensTotal }
           : { measured: false, tokensIn: 0, tokensOut: 0, tokensTotal: 0 };
}
function modeledUnai(out) {
  const o = out.observability || {};
  return { measured: false, tokensIn: o.tokensIn || 0, tokensOut: o.tokensOut || 0, tokensTotal: o.tokensTotal || 0 };
}
function send(res, code, obj) { res.writeHead(code, { "Content-Type": "application/json" }); res.end(JSON.stringify(obj)); }

async function handleCompare(res) {
  // Scope UNAI's side to just the capabilities that actually cost real
  // tokens in the source app when we know them (see REAL_COST_CAPABILITY_IDS)
  // -- otherwise this compares 1 real narrow capability against a modeled
  // estimate for the whole manifest, which is an apples-to-oranges mismatch.
  const scoped = REAL_COST_CAPABILITY_IDS.length ? REAL_COST_CAPABILITY_IDS : null;
  const out = scoped ? runUnaiScoped(scoped) : runUnai();
  let unai = modeledUnai(out);
  try {
    const live = await enrichEvidence(out.evidence || []);
    if (live && live.used !== "template" && live.calls) unai = { measured: true, tokensIn: live.tokensIn, tokensOut: live.tokensOut, tokensTotal: live.tokensIn + live.tokensOut };
  } catch (_) {}
  const measured = await runYourAppMeasured();
  const yourApp = measured.measured ? measured : Object.assign(modeledYourApp(out), { reason: measured.reason });
  const savingsPct = yourApp.tokensTotal ? Math.round(100 * (yourApp.tokensTotal - unai.tokensTotal) / yourApp.tokensTotal) : 0;
  send(res, 200, { ok: true, yourApp, unai, savingsPct, manifestId: MANIFEST.id, name: MANIFEST.name, scopedCapabilities: scoped });
}

// Runs just a subset of this manifest's capabilities through UNAI (not the
// whole plan) -- this is what lets a converted app's OWN backend code call
// into UNAI for one specific piece of work (see unai_backend.py, generated
// alongside this file for Python apps whose orchestrator imports per-agent
// run_agent() functions -- see applyPythonBackendSwap in foundry_convert.js)
// instead of just comparing against it from the outside.
function runUnaiSubset(capabilityIds) {
  const subset = MANIFEST.capabilities.filter(c => capabilityIds.includes(c.id))
    .map(c => ({ capability: "cv_" + c.id, agentEquiv: c.label, systems: (c.systems && c.systems.length) ? c.systems : ["ANALYTICS"] }));
  if (!subset.length) return { error: "no matching capabilities: " + capabilityIds.join(",") };
  const goal = { name: MANIFEST.name, description: MANIFEST.description, gen1Agents: subset.map(s => s.agentEquiv), plan: subset };
  const out = new UNAI({}).run(goal);
  const steps = (out.planPreview || []).map(p => ({ capability: p.capability.replace(/^cv_/, ""), confidence: p.confidence, autonomous: p.autonomous, decision: p.decision }));
  const explanation = subset.map(s => { const r = (out.results || {})[s.capability]; const ev = r && r.evidence; return ev && ev.explanation; }).filter(Boolean).join("\n\n");
  return { ok: true, steps, explanation, observability: out.observability || {} };
}

const server = http.createServer((req, res) => {
  // The Studio's own "Your app vs UNAI" tab (localhost:3000) fetches this
  // wrapper's /api/unai/* routes directly by absolute URL -- a genuine
  // cross-origin request from the browser's perspective, since this wrapper
  // runs on its own port. Without CORS headers the browser silently blocks
  // it ("Failed to fetch"), even though a server-side curl/fetch (no CORS
  // enforcement) to the same URL works fine -- which is exactly why this
  // went unnoticed testing via curl. Wide-open (*) is fine here: this is a
  // local dev/demo runtime, no cookies or credentialed requests involved.
  res.setHeader("Access-Control-Allow-Origin", "*");
  res.setHeader("Access-Control-Allow-Methods", "GET,POST,OPTIONS");
  res.setHeader("Access-Control-Allow-Headers", "Content-Type");
  if (req.method === "OPTIONS") { res.writeHead(204); return res.end(); }
  if (req.url === "/api/unai/manifest" && req.method === "GET") return send(res, 200, MANIFEST);
  if (req.url === "/api/unai/run" && req.method === "POST") { try { return send(res, 200, runUnai()); } catch (e) { return send(res, 500, { error: e.message }); } }
  if (req.url === "/api/unai/run-subset" && req.method === "POST") {
    let body = ""; req.on("data", b => body += b); req.on("end", () => {
      let j = {}; try { j = JSON.parse(body || "{}"); } catch (_) {}
      const ids = Array.isArray(j.capabilityIds) ? j.capabilityIds.map(String) : [];
      try { return send(res, 200, runUnaiSubset(ids)); } catch (e) { return send(res, 500, { error: e.message }); }
    }); return;
  }
  if (req.url === "/api/unai/compare" && req.method === "POST") { handleCompare(res).catch(e => send(res, 500, { error: e.message })); return; }
  const base = STATIC_DIR_REL ? path.join(WORK_DIR, STATIC_DIR_REL) : path.join(WORK_DIR, "unai_public");
  const reqPath = req.url === "/" ? "/index.html" : decodeURIComponent(req.url.split("?")[0]);
  const fp = path.join(base, reqPath);
  if (!fp.startsWith(path.resolve(base))) { res.writeHead(403); return res.end("Forbidden"); }
  fs.readFile(fp, (err, data) => {
    if (err) { res.writeHead(404, { "Content-Type": "text/plain" }); return res.end("Not found"); }
    res.writeHead(200, { "Content-Type": MIME[path.extname(fp)] || "application/octet-stream" });
    res.end(data);
  });
});
// A live multi-call measurement harness can take a couple minutes for a
// multi-agent source app -- don't let Node's default request/headers timeout
// (5min/60s) race it. Same reasoning as the main server.js's own
// server.requestTimeout = 0 for its long-running routes.
server.requestTimeout = 0;
server.headersTimeout = 0;
const PORT = process.env.PORT || 4100;
server.listen(PORT, () => console.log("[unai-converted] " + MANIFEST.name + " on http://localhost:" + PORT));
