# Generated by the UNAI Foundry -- routes calls that used to reach this
# app's own per-agent LLM pipeline through the shared UNAI runtime instead.
# UNAI runs as its own process on its own port (see the UNAI_BACKEND_URL env
# var this app's live preview is launched with); this file never touches the
# original agent modules' own code.
import json
import os
import urllib.request

UNAI_BACKEND_URL = os.environ.get("UNAI_BACKEND_URL", "http://localhost:4100")

def make_unai_agent(capability_ids, fallback_confidence=70):
    """Returns a function with the SAME call shape as this app's own
    run_agent(case, human_approval=...) -- so nothing else in the
    orchestrator (state wiring, routing, human-approval gating) needs to
    change, only what it dispatches to."""
    ids = list(capability_ids)
    def run_agent(case=None, human_approval=None):
        body = json.dumps({"capabilityIds": ids}).encode("utf-8")
        req = urllib.request.Request(UNAI_BACKEND_URL + "/api/unai/run-subset", data=body,
                                      headers={"Content-Type": "application/json"}, method="POST")
        try:
            with urllib.request.urlopen(req, timeout=20) as r:
                out = json.loads(r.read().decode("utf-8"))
        except Exception as e:
            return {"confidence_score": fallback_confidence, "approval_required": True,
                    "package": "[UNAI backend unreachable: %s]" % e,
                    "prompt_tokens": 0, "completion_tokens": 0, "total_tokens": 0}
        steps = out.get("steps") or []
        if not steps:
            return {"confidence_score": fallback_confidence, "approval_required": True,
                    "package": out.get("error", ""), "prompt_tokens": 0, "completion_tokens": 0, "total_tokens": 0}
        confidence_pct = round(100 * sum((s.get("confidence") or 0) for s in steps) / len(steps))
        autonomous = all(s.get("autonomous") for s in steps)
        obs = out.get("observability") or {}
        tin = int(obs.get("tokensIn") or 0)
        tout = int(obs.get("tokensOut") or 0)
        return {
            "confidence_score": confidence_pct,
            "approval_required": not autonomous,
            "package": out.get("explanation") or "",
            "prompt_tokens": tin, "completion_tokens": tout, "total_tokens": tin + tout,
        }
    return run_agent
