/* Generated by the UNAI Foundry convert-folder pipeline. Do not hand-edit --
 * re-running the conversion overwrites this file. */
const http = require("http");
const fs = require("fs");
const path = require("path");
const { spawn } = require("child_process");
const { UNAI } = require("./engine.cjs");
const { enrichEvidence } = require("./llm.cjs");

const MANIFEST = {
  "name": "NVIDIA",
  "description": "Converted from local folder (node)",
  "source": "convert",
  "sourceFormat": "folder:node",
  "createdAt": "2026-09-09T19:42:11.872Z",
  "layers": 7,
  "capabilities": [
    {
      "id": "generate_structured_json",
      "label": "generate Structured Json",
      "layer": "Action",
      "systems": [],
      "concept": null
    },
    {
      "id": "get_nvidia_client",
      "label": "get Nvidia Client",
      "layer": "Perception",
      "systems": [],
      "concept": null
    },
    {
      "id": "run_demand_forecast",
      "label": "run Demand Forecast",
      "layer": "Action",
      "systems": [
        "ANALYTICS"
      ],
      "concept": null
    },
    {
      "id": "run_demand_sensing",
      "label": "run Demand Sensing",
      "layer": "Action",
      "systems": [
        "ANALYTICS"
      ],
      "concept": null
    },
    {
      "id": "run_forecast_npi",
      "label": "run Forecast Npi",
      "layer": "Action",
      "systems": [
        "ANALYTICS"
      ],
      "concept": null
    },
    {
      "id": "run_orchestrator",
      "label": "run Orchestrator",
      "layer": "Action",
      "systems": [],
      "concept": null
    },
    {
      "id": "run_refurb_repair",
      "label": "run Refurb Repair",
      "layer": "Action",
      "systems": [
        "SAP_S4"
      ],
      "concept": null
    },
    {
      "id": "build_case_specific_failure_repair_analysis",
      "label": "build Case Specific Failure Repair Analysis",
      "layer": "Action",
      "systems": [
        "SAP_S4"
      ],
      "concept": null
    },
    {
      "id": "start_server",
      "label": "start Server",
      "layer": "Action",
      "systems": [],
      "concept": null
    },
    {
      "id": "call_nvidia_api",
      "label": "call Nvidia Api",
      "layer": "Action",
      "systems": [],
      "concept": null
    },
    {
      "id": "call_ollama_api",
      "label": "call Ollama Api",
      "layer": "Action",
      "systems": [],
      "concept": null
    }
  ],
  "systems": [
    "ANALYTICS",
    "SAP_S4"
  ],
  "absorbedSubsystems": [
    "Own per-call LLM plumbing / retries",
    "Per-agent reasoning + retries"
  ],
  "governance": {
    "autonomyThresholdPct": 85,
    "valueLimitUsd": 50000,
    "guardrails": [
      "PII redaction",
      "Prompt-injection screen",
      "Action safety (no destructive op)",
      "Confidence gate",
      "Value/policy gate"
    ]
  },
  "id": "CVA-BD56A6DF"
};
const WORK_DIR = __dirname;
const STATIC_DIR_REL = null;
const MEASURE_SCRIPT = null;
const MIME = { ".html": "text/html", ".js": "application/javascript", ".css": "text/css", ".json": "application/json",
  ".svg": "image/svg+xml", ".png": "image/png", ".jpg": "image/jpeg", ".ico": "image/x-icon" };

function buildGoal() {
  return {
    name: MANIFEST.name, description: MANIFEST.description,
    gen1Agents: MANIFEST.capabilities.map(c => c.label),
    plan: MANIFEST.capabilities.map(c => ({ capability: "cv_" + c.id, agentEquiv: c.label, systems: (c.systems && c.systems.length) ? c.systems : ["ANALYTICS"] })),
  };
}
function runUnai() { return new UNAI({}).run(buildGoal()); }

function runYourAppMeasured() {
  return new Promise(resolve => {
    if (!MEASURE_SCRIPT) return resolve({ measured: false, tokensIn: 0, tokensOut: 0, tokensTotal: 0, reason: "no measurement harness available for this app" });
    const isPy = MEASURE_SCRIPT.endsWith(".py");
    const cmd = isPy ? (process.platform === "win32" ? "python" : "python3") : process.execPath;
    // Generous timeout: a multi-script/multi-agent app can make many sequential
    // real LLM calls (the GDC 4-agent app alone takes ~60-90s) — same reasoning
    // as the main server.js's own long-running-route timeouts.
    let child; try { child = spawn(cmd, [MEASURE_SCRIPT], { cwd: WORK_DIR, timeout: 240000 }); }
    catch (e) { return resolve({ measured: false, tokensIn: 0, tokensOut: 0, tokensTotal: 0, reason: e.message }); }
    let err = ""; child.stderr.on("data", b => err += b);
    const finish = () => {
      try {
        const report = JSON.parse(fs.readFileSync(path.join(WORK_DIR, "unai_measure_report.json"), "utf8"));
        const tin = report.tokensIn || 0, tout = report.tokensOut || 0;
        resolve({ measured: (tin + tout) > 0, tokensIn: tin, tokensOut: tout, tokensTotal: tin + tout,
          reason: (tin + tout) > 0 ? null : "harness ran but captured no real provider usage" });
      } catch (e) { resolve({ measured: false, tokensIn: 0, tokensOut: 0, tokensTotal: 0, reason: "measurement harness failed: " + (err.slice(0, 200) || e.message) }); }
    };
    child.on("close", finish); child.on("error", finish);
  });
}
function modeledYourApp(out) {
  const b = out.observability && out.observability.benchmark && out.observability.benchmark.baseline;
  return b ? { measured: false, tokensIn: b.tokensIn, tokensOut: b.tokensOut, tokensTotal: b.tokensTotal }
           : { measured: false, tokensIn: 0, tokensOut: 0, tokensTotal: 0 };
}
function modeledUnai(out) {
  const o = out.observability || {};
  return { measured: false, tokensIn: o.tokensIn || 0, tokensOut: o.tokensOut || 0, tokensTotal: o.tokensTotal || 0 };
}
function send(res, code, obj) { res.writeHead(code, { "Content-Type": "application/json" }); res.end(JSON.stringify(obj)); }

async function handleCompare(res) {
  const out = runUnai();
  let unai = modeledUnai(out);
  try {
    const live = await enrichEvidence(out.evidence || []);
    if (live && live.used !== "template" && live.calls) unai = { measured: true, tokensIn: live.tokensIn, tokensOut: live.tokensOut, tokensTotal: live.tokensIn + live.tokensOut };
  } catch (_) {}
  const measured = await runYourAppMeasured();
  const yourApp = measured.measured ? measured : Object.assign(modeledYourApp(out), { reason: measured.reason });
  const savingsPct = yourApp.tokensTotal ? Math.round(100 * (yourApp.tokensTotal - unai.tokensTotal) / yourApp.tokensTotal) : 0;
  send(res, 200, { ok: true, yourApp, unai, savingsPct, manifestId: MANIFEST.id, name: MANIFEST.name });
}

// Runs just a subset of this manifest's capabilities through UNAI (not the
// whole plan) -- this is what lets a converted app's OWN backend code call
// into UNAI for one specific piece of work (see unai_backend.py, generated
// alongside this file for Python apps whose orchestrator imports per-agent
// run_agent() functions -- see applyPythonBackendSwap in foundry_convert.js)
// instead of just comparing against it from the outside.
function runUnaiSubset(capabilityIds) {
  const subset = MANIFEST.capabilities.filter(c => capabilityIds.includes(c.id))
    .map(c => ({ capability: "cv_" + c.id, agentEquiv: c.label, systems: (c.systems && c.systems.length) ? c.systems : ["ANALYTICS"] }));
  if (!subset.length) return { error: "no matching capabilities: " + capabilityIds.join(",") };
  const goal = { name: MANIFEST.name, description: MANIFEST.description, gen1Agents: subset.map(s => s.agentEquiv), plan: subset };
  const out = new UNAI({}).run(goal);
  const steps = (out.planPreview || []).map(p => ({ capability: p.capability.replace(/^cv_/, ""), confidence: p.confidence, autonomous: p.autonomous, decision: p.decision }));
  const explanation = subset.map(s => { const r = (out.results || {})[s.capability]; const ev = r && r.evidence; return ev && ev.explanation; }).filter(Boolean).join("\n\n");
  return { ok: true, steps, explanation, observability: out.observability || {} };
}

const server = http.createServer((req, res) => {
  if (req.url === "/api/unai/manifest" && req.method === "GET") return send(res, 200, MANIFEST);
  if (req.url === "/api/unai/run" && req.method === "POST") { try { return send(res, 200, runUnai()); } catch (e) { return send(res, 500, { error: e.message }); } }
  if (req.url === "/api/unai/run-subset" && req.method === "POST") {
    let body = ""; req.on("data", b => body += b); req.on("end", () => {
      let j = {}; try { j = JSON.parse(body || "{}"); } catch (_) {}
      const ids = Array.isArray(j.capabilityIds) ? j.capabilityIds.map(String) : [];
      try { return send(res, 200, runUnaiSubset(ids)); } catch (e) { return send(res, 500, { error: e.message }); }
    }); return;
  }
  if (req.url === "/api/unai/compare" && req.method === "POST") { handleCompare(res).catch(e => send(res, 500, { error: e.message })); return; }
  const base = STATIC_DIR_REL ? path.join(WORK_DIR, STATIC_DIR_REL) : path.join(WORK_DIR, "unai_public");
  const reqPath = req.url === "/" ? "/index.html" : decodeURIComponent(req.url.split("?")[0]);
  const fp = path.join(base, reqPath);
  if (!fp.startsWith(path.resolve(base))) { res.writeHead(403); return res.end("Forbidden"); }
  fs.readFile(fp, (err, data) => {
    if (err) { res.writeHead(404, { "Content-Type": "text/plain" }); return res.end("Not found"); }
    res.writeHead(200, { "Content-Type": MIME[path.extname(fp)] || "application/octet-stream" });
    res.end(data);
  });
});
// A live multi-call measurement harness can take a couple minutes for a
// multi-agent source app -- don't let Node's default request/headers timeout
// (5min/60s) race it. Same reasoning as the main server.js's own
// server.requestTimeout = 0 for its long-running routes.
server.requestTimeout = 0;
server.headersTimeout = 0;
const PORT = process.env.PORT || 4100;
server.listen(PORT, () => console.log("[unai-converted] " + MANIFEST.name + " on http://localhost:" + PORT));
